server:
  servlet:
    context-path: /
  port: 8081

spring:
  shardingsphere:
    mode:
      type: Standalone # Standalone,Memory
    datasource:
      names: db0,db1
      db0:
        username: root
        password: 123456
        # 注意是 jdbc-url, 不是url
        jdbc-url: jdbc:mysql://localhost:3306/zhang_0?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
      db1:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://localhost:3306/zhang_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
    # 配置分库分表 sharding 规则
    sharding:
      # 分库分表
      tables:
        student:
          # 分库分表范围
          actual-data-nodes: db$->{0..1}.student_$->{0..1}
          # 分库策略
          database-strategy:
            standard:
              sharding-column: id
              # precise 策略
              precise-algorithm-class-name: com.shardingstandard.config.precise.MyDatabasePreciseAlgorithm
              # range 策略 (between and)
              range-algorithm-class-name: com.shardingstandard.config.range.MyDatabaseRangeAlgorithm
          # 分表策略
          table-strategy:
            standard:
              sharding-column: id
              # precise 策略
              precise-algorithm-class-name: com.shardingstandard.config.precise.MyTablePreciseAlgorithm
              # range 策略 (between and)
              range-algorithm-class-name: com.shardingstandard.config.range.MyTableRangeAlgorithm
      # 默认数据源，未分片的表默认执行库
      default-data-source-name: db0
    # 打印 sharding 分库分表日志
    props:
      sql-show: true # 输出SQL日志

mybatis-plus:
  # 注意： classpath*：不仅在本地项目resources中查找,还包括jar包中的， classpath则只包含本地的
  mapper-locations:
    #  默认 classpath*:/mapper/**/*.xml
    - classpath*:mapper/**/*Mapper.xml
  global-config:
    #设置逻辑删除（mybatis-plus的 删除 会成为逻辑删除 查询 方法自动过滤删除数据）
    db-config:
      # 逻辑删除字段
      logic-delete-field: isDel
      # 已删除
      logic-delete-value: 0
      # 未删除
      logic-not-delete-value: 1
  configuration:
    # 下划线驼峰命名 默认 true
    map-underscore-to-camel-case: true
    # 开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



