#spring:
#  profiles:
#    active: dev

server:
  servlet:
    context-path: /
  port: 8086

my:
  open: true
  msg: 'asdas'

single:
  zhang: 'single.zhang'
  open: false

single2: # 没有该属性的时候, 无法实例化 (注意:此时spring.factories无效)
  open: true # 该属性不为 true的时候, 无法实例化 (注意:此时spring.factories无效)
  zhang: 'single2.zhang'

# 1.single3整个属性为空的时候,由spring.factories初始化bean
# 2.当single3不为空的时候, 属性 open:true才初始化bean, 否则不初始化为bean (注意:此时spring.factories无效)
single3:
  open: false
  zhang: 'single3.zhang'

