
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhang?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 55.10.24.36
    port: 5672
    username: 9e888dfc-2099-4963-90f9-22a63f00bba7
    password: 770dd4d7-cd09-4ec7-8099-39660bed476e
    virtual-host: 5590ccaa-6892-4fe3-9639-59091501c66e
    publisher-confirms: true
    publisher-returns: true
    #消费端配置
    listener:
      simple:
        #消费端,每个@RabbitListener开启几个线程去处理数据,即多少个channel
        concurrency: 5
        #最大消费端数
        max-concurrency: 10
        #自动签收auto  手动 manual
        acknowledge-mode: manual
        # 限流作用,每个消费线程从RabbitMQ预获取的消息数量,即一个消费者最多可处理的nack消息数量, 如果有事务的话，必须>=transaction数量.
        prefetch: 1
server:
  port: 8081
