server:
  servlet:
    context-path: /spring-boot-exception
  port: 8080


spring:
  # ------------------------------------ thymeleaf配置 BEGIN ------------------------------------
  thymeleaf:
    cache: true
    mode: HTML
    prefix: classpath:/templates/
    encoding: utf-8
    servlet:
      content-type: text/html
    suffix: .html
  # ------------------------------------ thymeleaf配置 END ------------------------------------

