spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhang?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 # 配置初始化大小、最小、最大
      min-idle: 5
      max-active: 20
      max-wait: 60000 # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  rabbitmq:
    host: 55.10.24.36
    port: 5672
    username: 9e888dfc-2099-4963-90f9-22a63f00bba7
    password: 770dd4d7-cd09-4ec7-8099-39660bed476e
    virtual-host: 5590ccaa-6892-4fe3-9639-59091501c66e
    publisher-confirms: true # 发送者开启 confirmCallback(消息是否从producer发送到exchange)
    publisher-returns: true # 发送者开启 returnCallback(消息是否从exchange发送到queue)
    #连接超时时间
    connection-timeout: 15000
    template:
      # false: 没有合适的消息路由，直接丢弃消息
      # true: 消息路由失败通知监听者，而不是将消息丢弃
      # 触发setReturnCallback回调必须设置 mandatory=true, 否则Exchange没有找到Queue就会丢弃掉消息, 而不会触发回调
      mandatory: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

base:
  config:
    rabbitmq:
      #重新投递时间（分钟）
      overtime: 1