server:
  port: 8080

# 进入debug模式
logging:
  level:
    org.springframework.security: DEBUG


base:
  encrypt:
    aes-key: 'bfcf1ba4d7059352613588effbfe8f0b'
    des-key: '12345678'
    open: true
    debug: true

