
# 环境env变量
# ${actfile:*} 对应deploy_*.yaml中的变量名env.name.actfile, 值是"value"
# [默认/本地]配置是local
spring:
  profiles:
    active: dev

  # ------------------------------------ 热加载等配置 BEGIN ------------------------------------
  # 指定热加载触发器, main文件修改后,不会立马热加载, 手动修改resources/application-trigger.yml出发
  devtools:
    restart:
      trigger-file: application-trigger.yml
  banner: # 启动图文字符
    image:
      location: banner.txt
  # ------------------------------------ 热加载等配置 END ------------------------------------



# ------------------------------------ mybatis 相关配置 BEGIN ------------------------------------
mybatis:
  #configuration:
  # 打印sql语句
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper映射和entity映射, MapperScan位置在Application中配置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# ------------------------------------ mybatis 相关配置 END ------------------------------------


# ------------------------------------ page 分页插件 BEGIN ------------------------------------
pagehelper:
  helper-dialect: sqlServer     # 支持Oracle,Mysql,MariaDB,SQLite,Hsqldb,PostgreSQL等等
  reasonable: true              # 分页合理化参数，默认值为false, true会合理化( pageNum<=0 和 pageNum>pages)
  support-methods-arguments: true
  params: count=countSql
  auto-runtime-dialect: true    # 动态数据源 autoRuntimeDialect:true，确保使用不同数据源时，会使用匹配的分页进行查询
  close-conn: false             # 默认true:每次获取数据源后自动关闭, 这里设置成false, 不关闭
# ------------------------------------ page 分页插件 END------------------------------------


# ====================================== User-defined parameters BEGIN ======================================
# --------------------- 数据库全局配置 BEGIN ---------------------
global.druid.db:
  initial-size: 1
  min-idle: 1
  max-active: 20 # 默认8
  max-wait: 6000 # 默认-1
  validation-query: SELECT 1
  validation-query-oracle: SELECT 1 FROM DUAL
  test-on-borrow: false # 默认false
  test-while-idle: true # 默认true
  test-on-return: false # 默认false
  time-between-eviction-runs-millis: 60000 # 默认60000
  min-evictable-idle-time-millis: 360000  # 默认1800000
  remove-abandoned: true # 默认 false
  remove-abandoned-timeout: 1800 # 默认 300
  log-abandoned: false # 默认false
# --------------------- 数据库全局配置 END ---------------------
# ====================================== User-defined parameters END ======================================

