CREATE TABLE T_ORDER
(
    ID         INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    NAME       varchar(128) DEFAULT NULL,
    MESSAGE_ID varchar(128) DEFAULT NULL,
    PRIMARY KEY (id)
) TABLESPACE TBS_CUR_DAT;


COMMENT ON COLUMN T_ORDER.ID IS '主键id';
COMMENT ON COLUMN T_ORDER.NAME IS '姓名';
COMMENT ON COLUMN T_ORDER.MESSAGE_ID IS '消息id';

CREATE TABLE T_BROKER_MESSAGE_LOG
(
    MESSAGE_ID  varchar(128) NOT NULL,
    MESSAGE     varchar(4000) DEFAULT NULL,
    TRY_COUNT   NUMBER(4, 0)  DEFAULT '0',
    STATUS      varchar(10)   DEFAULT NULL,
    NEXT_RETRY  TIMESTAMP     DEFAULT NULL,
    CREATE_TIME TIMESTAMP     DEFAULT NULL,
    UPDATE_TIME TIMESTAMP     DEFAULT NULL,
    PRIMARY KEY (MESSAGE_ID)
) TABLESPACE TBS_CUR_DAT;


COMMENT ON COLUMN T_BROKER_MESSAGE_LOG.MESSAGE_ID IS '消息id';
COMMENT ON COLUMN T_BROKER_MESSAGE_LOG.MESSAGE IS '消息内容';
COMMENT ON COLUMN T_BROKER_MESSAGE_LOG.TRY_COUNT IS '尝试次数';
COMMENT ON COLUMN T_BROKER_MESSAGE_LOG.STATUS IS '状态';
COMMENT ON COLUMN T_BROKER_MESSAGE_LOG.NEXT_RETRY IS '下次尝试时间';
COMMENT ON COLUMN T_BROKER_MESSAGE_LOG.CREATE_TIME IS '创建日期';
COMMENT ON COLUMN T_BROKER_MESSAGE_LOG.UPDATE_TIME IS '更新日期';