spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhang?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: x.10.24.36
    port: 5672
    username: 9e888dfc-2099-4963-90f9-xx
    password: 770dd4d7-cd09-4ec7-xx-39660bed476e
    virtual-host: 5590ccaa-6892-4fe3-9639-59091501c66e
    publisher-confirms: true # 发送者开启 confirmCallback(消息是否从producer发送到exchange)
    publisher-returns: true # 发送者开启 returnCallback(消息是否从exchange发送到queue)
    connection-timeout: 15000
    template:
      # false: 没有合适的消息路由，直接丢弃消息
      # true: 消息路由失败通知监听者，而不是将消息丢弃
      mandatory: true

rmq:
  # 队列定义
  queue:
    live: queue-live # 正常业务队列——绑定死信交换机
    delay: queue-delay # 延迟队列——绑定死信交换机
    dead: queue-dead # 死信队列
    prefetch: queue-prefetch # prefetch队列
  # 交换机定义
  exchange:
    live: exchange-live # 正常业务交换机
    delay: exchange-delay # 延迟交换机
    dead: exchange-dead # 死信交换机
    prefetch: exchange-prefetch # prefetch交换机
  # 路由key
  route:
    live: 'live.*'
    delay: 'delay.*'
    dead: 'dead.*'
    prefetch: 'prefetch.*'




