server:
  port: 8080

# -------------------- 数据库变量 BEGIN --------------------
this.druid.db:
  username: TEST
  password: Lj08#123456
  url: jdbc:oracle:thin:@//xx.14.63.174:1521/XXX
# -------------------- 数据库变量 END --------------------

spring:
  # ------------------------------------数据库基本配置 BEGIN ------------------------------------
  datasource:
    #readSize为从库数量
    name: mySqlName
    # 配置第三方数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: oracle.jdbc.OracleDriver
      url: ${this.druid.db.url}
      username: "${this.druid.db.username}"
      password: "${this.druid.db.password}"
      # 配置初始值
      initial-size: "${global.druid.db.initial-size}"
      min-idle: "${global.druid.db.min-idle}"
      max-active: "${global.druid.db.max-active}"
      # 获取连接等待超时时间
      max-wait: "${global.druid.db.max-wait}"
      # 监控关闭空闲连接时间间隔
      time-between-eviction-runs-millis: "${global.druid.db.time-between-eviction-runs-millis}"
      # 每个连接池最小的生命周期
      min-evictable-idle-time-millis: "${global.druid.db.min-evictable-idle-time-millis}"
      validation-query: "${global.druid.db.validation-query}"
      test-while-idle: "${global.druid.db.test-while-idle}"
      test-on-borrow: "${global.druid.db.test-on-borrow}"
      test-on-return: "${global.druid.db.test-on-return}"
      remove-abandoned: "${global.druid.db.remove-abandoned}"
      remove-abandoned-timeout: "${global.druid.db.remove-abandoned-timeout}"
      log-abandoned: "${global.druid.db.log-abandoned}"
  # ------------------------------------数据库基本配置 END ------------------------------------





# ------------------------------------ mybatis 相关配置 BEGIN ------------------------------------
mybatis:
  #configuration:
  # 打印sql语句
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper映射和entity映射, MapperScan位置在Application中配置
  # 注意： classpath*：不仅在本地项目resources中查找,还包括jar包中的， classpath则只包含本地的
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-executor-type: simple # 默认是simple

# ------------------------------------ mybatis 相关配置 END ------------------------------------



# ====================================== User-defined parameters BEGIN ======================================
# --------------------- 数据库全局配置 BEGIN ---------------------
global.druid.db:
  # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
  initial-size: 1
  # 定义最小连接池数量
  min-idle: 1
  # 定义最大连接池数量
  max-active: 20 # 默认8
  # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
  max-wait: 6000 # 默认-1
  # 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
  validation-query: SELECT 1 FROM DUAL
  # 这里建议配置为TRUE，防止取到的连接不可用。获取链接的时候，不校验是否可用，开启会有损性能
  test-on-borrow: false # 默认false
  # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
  test-while-idle: true # 默认true
  # 归还连接时检测连接是否有效，做了这个配置会降低性能。
  test-on-return: false # 默认false
  # 有两个含义：1) Destroy线程会检测连接的间隔时间;2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
  time-between-eviction-runs-millis: 60000 # 默认60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  min-evictable-idle-time-millis: 360000  # 默认1800000
  # 打开removeAbandoned功能, 链接使用超过时间限制是否回收, 如果为true, 同时配置timeout
  remove-abandoned: true # 默认 false
  # 超过时间限制时间（单位秒），目前为30分钟，如果有业务处理时间超过30分钟，可以适当调整, 1800秒，也就是30分钟
  remove-abandoned-timeout: 1800 # 默认 300
  # 关闭abandoned连接时输出错误日志, 即链接回收的时候控制台打印信息，测试环境可以加上true，线上环境false。会影响性能
  log-abandoned: false # 默认false
# --------------------- 数据库全局配置 END ---------------------
# ====================================== User-defined parameters END ======================================
