
# 环境env变量
# ${actfile:*} 对应deploy_*.yaml中的变量名env.name.actfile, 值是"value"
# [默认/本地]配置是local
spring:
  profiles:
    active: ${actfile:dev}


  # ------------------------------------ thymeleaf配置 BEGIN ------------------------------------
  thymeleaf:
    cache: true
    mode: HTML5
    prefix: classpath:/templates/
    encoding: utf-8
    servlet:
      content-type: text/html
    suffix: .html
  # ------------------------------------ thymeleaf配置 END ------------------------------------

  # ------------------------------------ 热加载等配置 BEGIN ------------------------------------
  # 指定热加载触发器, main文件修改后,不会立马热加载, 手动修改resources/application-trigger.yml出发
  devtools:
    restart:
      trigger-file: application-trigger.yml
  banner: # 启动图文字符
    image:
      location: zbanner.txt
  # ------------------------------------ 热加载等配置 END ------------------------------------